openapi: 3.0.1
info:
  title: Progress-Account
  description: Progress account specification to define the progress account API
  contact:
    email: suport@estiatraining.com
  version: 1.0.0
servers:
  - url: https://localhost:8080/v1
    description: Production server
tags:
  - name: progresses
    description: Progress Account
paths:
  /progresses:
    get:
      summary: Retrieve all progresses
      tags:
        - progresses
      security:
        - BearerAuth
      operationId: getAllProgress
      responses:
        200:
          $ref: '#/components/responses/SuccessGetAll'
        401:
          $ref: '#/components/responses/Unauthorized'                         
        500:
          $ref: '#/components/responses/ServerError'  
  /progress:                
    post:
      summary: Create a new progress
      tags:
        - progresses      
      security:
        - BearerAuth
      operationId: createProgressAccount
      requestBody:
        $ref: '#/components/requestBody/progressBody' 
        required: true
      responses:
        201:
          $ref: '#/components/responses/Created'
        401:
          $ref: '#/components/responses/Unauthorized'                         
        500:
          $ref: '#/components/responses/ServerError'         
  /progress/{id}:                
    get:
      summary: Get a progress by ID
      tags:
        - progresses      
      security:
        - BearerAuth
      operationId: getProgressById
      parameters:
        - name: id
          in: path
          description: Progress ID
          required: true
          schema:
            type: integer
            format: int64     
      responses:
        200:
          $ref: '#/components/responses/Success'
        401:
          $ref: '#/components/responses/Unauthorized'    
        404:
          $ref: '#/components/responses/NotFound'                                  
        500:
          $ref: '#/components/responses/ServerError'                                                                    
    put:
      summary: Update a progress by ID
      tags:
        - progresses      
      security:
        - BearerAuth
      operationId: updateProgressById
      parameters:
        - name: id
          in: path
          description: Progress ID
          required: true
          schema:
            type: integer
            format: int64        
      requestBody:
        $ref: '#/components/requestBody/progressBody'        
      responses:
        202:
          $ref: '#/components/responses/Accepted'
        401:
          $ref: '#/components/responses/Unauthorized'    
        404:
          $ref: '#/components/responses/NotFound'                                  
        500:
          $ref: '#/components/responses/ServerError'       
    delete:
      summary: Delete a progress by ID
      tags:
        - progresses      
      security:
        - BearerAuth
      operationId: deleteProgressById
      parameters:
        - name: id
          in: path
          description: Progress ID
          required: true
          schema:
            type: integer
            format: int64               
      responses:   
        204:
          description: No Content
        401:
          $ref: '#/components/responses/Unauthorized'    
        404:
          $ref: '#/components/responses/NotFound'                                  
        500:
          $ref: '#/components/responses/ServerError'          
components:
  schemas:  
    requestBody:
      required:    
        - dateProgress
        - headCircumference
        - height
        - weight
        - patient
      type: object
      properties:             
        dateProgress:
          type: string
          format: date
          minimum: 10
          example: 10/02/2010
        headCircumference:          
          type: number 
          format: double
          example: 0.74
        height:          
          type: number 
          format: double
          example: 1.2
        weight:
          type: number 
          format: double
          example: 16.2
        patient:
          $ref: '#/components/schemas/patient'                       
    progress:
      required:    
        - id 
        - dateProgress
        - headCircumference
        - height
        - weight
        - patient
      type: object
      properties:  
        id:
          type: integer
          format: int64
          example: 1            
        dateProgress:
          type: string
          format: date
          minimum: 10
          example: 10/02/2010
        headCircumference:          
          type: number 
          format: double
          example: 0.74
        height:          
          type: number 
          format: double
          example: 1.2
        weight:
          type: number 
          format: double
          example: 16.2
        patient:
          $ref: '#/components/schemas/patient'   
    patient:
      required:    
        - id  
        - firstName
        - lastName 
        - dateBirth               
        - gender
        - phoneNumber
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1       
        dateBirth:
          type: string
          format: date
          minimum: 10
          example: 10/02/2010
        firstName:          
          type: string
          minimum: 2
          example: 'Cleison'
        lastName:          
          type: string
          minimum: 2
          example: 'Melo'   
        phoneNumber:
          type: number 
          format: int32
          example: 555-6563-5623
        gender:
          type: string
          example: M
          enum:
            - M
            - F                   
    body_response_error:
      required:
        - code_error
        - message        
      type: object
      properties:
        code_error:
          type: integer
          format: int64
          minimum: 1
          example: 13216      
        message:
          type: string
          example: message_to_show    
  requestBody:
    progressBody:
      description: Progress JSON object required
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/requestBody' 
  responses:          
    Success:
      description: OK
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/progress'
    Created:
      description: Created
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/progress'     
    Accepted:
      description: Accepted
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/progress'              
    SuccessGetAll:
      description: OK
      content:
        application/json:
          schema:
            type: array
            items:  
              oneOf:
               - $ref: '#/components/schemas/progress'   
               - $ref: '#/components/schemas/progress'                        
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/body_response_error'          
    Unauthorized:
      description: Unauthorized error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/body_response_error'            
    Forbidden:
      description: Forbidden error    
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/body_response_error'                  
    ServerError:
      description: Server error      
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/body_response_error'       
    NotFound:
      description: Not found      
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/body_response_error'                          
  securitySchemes:                               
    BearerAuth:
      type: http
      scheme: bearer  
      bearerFormat: JWT